// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkAflqpebnmB0fZia6j4tu_5fW3L0IpMI',
    appId: '1:198724125354:web:53ff97161ebd99524106d3',
    messagingSenderId: '198724125354',
    projectId: 'pocketgpt-7a3f1',
    authDomain: 'pocketgpt-7a3f1.firebaseapp.com',
    storageBucket: 'pocketgpt-7a3f1.appspot.com',
    measurementId: 'G-DKMFJZP10Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASrgXGj7hSYUU7Mg_Dyn6U-KghQkTx9FE',
    appId: '1:198724125354:android:c0d25fbf2c61442d4106d3',
    messagingSenderId: '198724125354',
    projectId: 'pocketgpt-7a3f1',
    storageBucket: 'pocketgpt-7a3f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-KufcEdSrorCu0clAdyPMUYVMHjrjPJc',
    appId: '1:198724125354:ios:83b45c4e0db337714106d3',
    messagingSenderId: '198724125354',
    projectId: 'pocketgpt-7a3f1',
    storageBucket: 'pocketgpt-7a3f1.appspot.com',
    iosClientId: '198724125354-q92gkbq2iefhl4g7t4c8q3a3eoi196ql.apps.googleusercontent.com',
    iosBundleId: 'com.example.pocketGpt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-KufcEdSrorCu0clAdyPMUYVMHjrjPJc',
    appId: '1:198724125354:ios:83b45c4e0db337714106d3',
    messagingSenderId: '198724125354',
    projectId: 'pocketgpt-7a3f1',
    storageBucket: 'pocketgpt-7a3f1.appspot.com',
    iosClientId: '198724125354-q92gkbq2iefhl4g7t4c8q3a3eoi196ql.apps.googleusercontent.com',
    iosBundleId: 'com.example.pocketGpt',
  );
}
